#!/bin/bash

cd /var/log/nginx
filepath=$(mktemp)
(/bin/zcat $(find . -name '*.gz' -type f | grep -v error); cat *.log) > $filepath
/usr/bin/goaccess $filepath --log-format=COMBINED -o /var/www/stats/index.html
